appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: BgqNtulHTFVZbfZHTGeIlCG800dVbxbznvGhNcuzhyF/FUiR6Wpjmva5dYfTCyjahaKgW2/QuPPZQ58vSmUZzVAl/I38CAcae1O0Te82LdR6aIMsBYSM6Z2b0tuLrEvI3s0W46V8pH7TbQCESArBQx91bOLryTh3X/W39nisJlAwde5G2yPLW2pibUt1bysjtNkJFeVnfXA6Vk3oXN9YODSgzUIpr37kFaYGQ3qV1waTkLOYTePOzOFNsd0dHempPVlL/Nd/U9ZsO8Ohc7b8B2GM6x08g/yWEAAlGLdVOMLrZyBaO7GKrmcimCOk+KWAOMJ49Mbo/mzv44qZKM4+Q7lUJdxIVYFZTEZofdyeKE+IACEBlIMFa4mNP42cnTxMDPJUF5YRRFl8y1bx12V0wRBuBgDYvsjTNEtkyUCTmKbDP0XAnLxMpo/nnjW6q0D38Qfl7NiOStclxGwtarx+n60GFzoxqYZgmZi8l0IeSEtTcqj2ggjjUMDFiDHnjQFk7DGQONT/YXLS8nOovQg6wwUyppBpoOk3n58WtS5G4nlTehYq4EHHfoBnNHY9QFvsfQpq1luBiZUx32fjKvIsjAEKLuWjm5AP0A2vvFmRaKWJbsAIaWJEtUPLtk01vwrcOR7wnZ1Vpr+G+UppIYutCP2sdeamepUbxiArQzdBenA=}
